#ref:https://medium.com/google-cloud/a-node-js-websocket-server-on-google-app-engine-c6c32a486e9a

# [START appengine_websockets_yaml]
runtime: nodejs
env: flex

# Use only a single instance, so that this local-memory-only chat app will work
# consistently with multiple users. To work across multiple instances, an
# extra-instance messaging system or data store would be needed.
manual_scaling:
  instances: 1

network:
  forwarded_ports:
    - 3000
  instance_tag: websocket
# [END appengine_websockets_yaml]